- .prettierrc
- nuxt.config.ts
- package-lock.json
- package.json
- pages/index.vue
- plugins/masonry.client.ts
This PR loads the [Masonry](https://masonry.desandro.com/) JavaScript library and uses it to stack/position Bulma cards on the front page dynamically. I've also added Prettier because I couldn't help myself, and copied the `.prettierrc` file from Northern Climate Reports.
> Use Masonry library for dynamic card layout (+ add Prettier)

- assets/cards.js
- components/Item.vue
- layouts/full.vue
- nuxt.config.ts
- pages/full.vue
- pages/index.vue
> Add optional "full view" page for cards that need it

- components/ResultsCount.vue
- pages/index.vue
- stores/store.ts
Modifies the PR to add Results Count to its own component.
> Move ResultsCount to its own component?

- assets/styles/items.scss
- assets/styles/main.scss
- components/Footer.vue
- components/Header.vue
- components/Item.vue
- components/Navbar.vue
- components/Tagbar.vue
- layouts/default.vue
- layouts/home.vue
- pages/tag/[tag].vue
Testing:
- Home page should work the same
- Clicking on a tag either in the "Tagbar" (list of tags above content) or within an actual tag bubble should take you to a Tagpage
> Adds tagbar, tag pages, and a navbar placeholder

- stores/map.ts
- types/custom.d.ts
For testing, just ensure the app runs and the maps still load!
> Remove unused code, enforce presence of named style for Geoserver layers

- assets/styles/main.scss
- components/Footer.vue
- components/FrontPage/Main.vue
- components/Header.vue
- layouts/default.vue
- layouts/home.vue
- nuxt.config.ts
Test by setting max screen width to something huge (2500+px) and observe that the max width is clamped.  Look at where/how I did that: is it right?  It implies that all main content is always clamped: ok?  (Some parts are deliberately left at full-bleed: top nav menu + footer etc.
> clamps max width and adds example code for using mixins for responsive

- README.md
Check the README and look for errors.  (We can continue to improve this!)
> Improve documentation overview in readme

- components/IndicatorsCmip6ChartControls.vue
I was getting errors with this line of code and when I traced things it doesn't look this this ought to be here?  But I'm unsure about nonlocal effects / how that might tie into other branches because it's in `main`?
STR:
- load the `implement_zeus_items` branch of code as-is,
- go to the flammability endpoint,
- load data for Chena Hot Springs.
An error emerges.
> Remove this line of code?

- components/Edition.vue
- components/global/StoryArcticClimateDataNode.vue
- Has pumpkin
- Update main ACDN story to point to CMIP6 data right away
> Wee content adjustments

- layouts/home.vue
Adds trumpet.
To test:
- Observe trumpet.
> Adds trumpet

- components/PermafrostChartControls.vue
Closes #119 
Read that ticket.
To test, check a chart that uses the PermafrostChartControl widget (such as http://localhost:3000/item/permafrost-magt).
> Switch to use Permafrost chart label type

- nuxt.config.ts
Adds CrazyEgg to the ARDAC Explorer.
Closes #160
> Adds CrazyEgg to ARDAC Explorer

- components/global/IndicatorCd.vue
- components/global/IndicatorHd.vue
This PR adds &deg;C as the units for both Hot and Cold days.
http://localhost:3000/item/indicator-cd
http://localhost:3000/item/indicator-hd
Closes #209
> Adds the units to both Hot and Cold days.

- components/GetAndUseData.vue
- components/RandomLocationMap.vue
- components/RandomPolygonMap.vue
- components/global/PlacesAndPolygons.vue
- nuxt.config.ts
- package-lock.json
- package.json
This PR makes a bunch of little responsiveness and style tweaks to the new Places & Polygons items, including:
- I've used Bulma classes to change the responsiveness breakpoints, so now the whole page switches to single column mode below 1024px width (instead of below 769px width as before), to make sure the page only shows side-by-side columns when there is enough room for the content to breathe.
- The page now uses Bulma tiles more consistently (instead of a tiles + columns hybrid), which makes it easier to ensure that the left and right sections of the page narrow down in lockstep as you change the width of your browser window. This is close to perfect, but the "Point Location Features" and "Polygon Boundary Features" tiles still fall out of lockstep with the tiles above them at …
> Better responsiveness + style tweaks for Places & Polygons page

- components/GetAndUseData.vue
- components/global/PlacesAndPolygons.vue
- Moves code for generating a list of regions out of GetNUse back to the item itself,
- Removes some unused code (formattedRegion),
- Reduce CSS
> Moves the CSV-by-region back into Places item

- components/global/PlacesAndPolygons.vue
Check the content revisions,
- Moved the buttons up to take more of a 'call to action' position,
- Switched layout to 2-column (spacing may need a little cleanup),
- Removed CSS & unused HTML.
> Use 2-column layout & minimize CSS/formatting

- components/RandomLocationMap.vue
- components/global/PlacesAndPolygons.vue
- stores/places.ts
> Make the RandomPoint boring, store fixups

- components/RandomLocationMap.vue
- components/RandomPolygonMap.vue
- components/global/PlacesAndPolygons.vue
- nuxt.config.ts
- package-lock.json
- package.json
- Destyles the button
- Remove close button
- Removes the feature ID, that doesn't feel actionable here (but actually could be enriched to be neat: forming URLs for random "gimme data"?)
- Switches base map in Point random component to OSM, *but* keeps USGS here.  
- Remove Font Awesome.
-
> Makes polygon selection button boring, etc

- components/RandomLocationMap.vue
- components/RandomPolygonMap.vue
- components/global/PlacesAndPolygons.vue
- stores/places.ts
- stores/polygons.ts
> Make errors gentle, lint, minor fixups

- components/Edition.vue
- components/global/StoryArcticClimateDataNode.vue
- layouts/home.vue
TBD needs update at end of dev cycle to get  all links updated
> Updates Edition, "what's new" blurb, add E3SM to ACDN story
