- assets/styles/_variables.scss
- assets/styles/main.scss
- components/Footer.vue
- layouts/home.vue
- nuxt.config.ts
It's easier as we settle the design to be able to reference global variables, both for configuring Bulma as well as direct usage in our components/Nuxt app.  This is the wee bit of glue that makes that work, + examples within components.
> Wires things up for using global scss variables

- pages/index.vue
This PR cleans up HTML template code by using `:bind` only for dynamic class names, alongside just `bind` for static class names. It turns out this works just fine! I don't know why it didn't seem to work on my first pass.
I also realized that only the Masonry grids themselves (parent divs) need unique class selectors. Grid items can all use the `grid-item` class regardless of which grid they belong to, and I think it's better (more portable) to keep these more general because it may help with SASS styling later down the road if needed.
> Simplify grid-item classes and clean up static vs. dynamic attributes

- assets/items.js
- components/Item.vue
- components/global/QueryingDaymetDailyPrecipitation.vue
- pages/full.vue
- utils/slugs.ts
This PR implements one way (and the only way I've found) to optionally & dynamically load an item's "full view" display from a file.
The motivation here is to be able to populate the full view for an item with things like embedded Leaflet maps, tables, interactive widgets, and general **_bespokery_**, and to do this in a sane, maintainable, and version-controlled way. Without this functionality, we were faced with the possibility of implementing complex full view displays as giant blobs of HTML inside items' `fullView` fields, which would start out gnarly in the simplest of cases and only get worse after that.
This PR works by taking the item slug from the URL (e.g., `querying-daymet-daily-precipitation`), converting that into the camel case style used by Vue components (e.g., …
> Optionally load item's full view content from a Vue component

- components/Search.vue
- pages/index.vue
- types/custom.d.ts
This PR removes categorization by tag (and item duplication) from the front page. It also removes a couple custom TypeScript types that are no longer needed now that this functionality has been removed.
I've also tweaked the layout of the search system a little bit, too, to remove my attempts at centering the search bar and "No results..." message. The centering had gotten a bit wonky and unpredictable at different resolutions, so I figure it's better to align these to the left for now.
To test, load the app, make sure the items are laid out well + not duplicated, and everything continues to look good when using the search system.
> Remove categorization and item duplication, and also remove search bar centering attempts

- components/ResultsCount.vue
- pages/index.vue
- stores/store.ts
This PR adds the following message below the search bar when search mode is engaged:
> Showing __ matches out of __ possible items.
I've also moved the "No results found" message into this new system, so when search mode is engaged and no results are found, it says:
> No matches found out of __ possible items.
To test, run the app and confirm that the message only shows when search mode is engaged and the text reads how you expect depending on the number of results, singular/plural, etc.
> Add count of matched items below search bar

- assets/styles/_variables.scss
- assets/styles/main.scss
- components/Header.vue
- components/HeaderBanner.vue
- components/Item.vue
- components/ResultsCount.vue
This PR switches us to a light background design.  It also does a little cleanup/clarification of what/where custom variables and/or Bulma overrides are doing in the build process.
* We should use variables for colors in components so that we can be consistent.
* Define custom variables in `assets/styles/_variables.scss`
* Variables defined there will override Bulma variable names, so this is also where Bulma overrides go.
* You can't use a Bulma variable in a component unless you define it here.
Test = load the page + see light background!
> Switch to light background

- assets/items.js
- components/ResultsCount.vue
- pages/full.vue
- pages/index.vue
- pages/tag/[tag].vue
- stores/store.ts
This PR adds an optional `priority` field for items. This field controls how items are ordered on the front/tag pages. Items without a `priority` field are sorted below all items that do have a `priority` field. Currently, lower priority numbers sort higher up on the page.
This works by first sorting the array of items as described above, and then taking advantage of Masonry's [horizontalOrder](https://masonry.desandro.com/options#horizontalorder) option to keep higher priority elements at the top while still fitting things together in an optimal way.
To test, try setting the priority of items in `items.js` in different ways and make sure the items are sorted on the page(s) the way you'd expect. Try this on both the front page and the item pages. Browser reload may be required after …
> Add optional item priority field to control page sorting

- components/ResultsTable.vue
- pages/index.vue
This PR changes the front page to display items in table format if there are five or less search results. I've omitted thumbnail images from the table display because they would either take up too much room in the table (IMO) or be too small to see the thumbnail details.
To test, load the app and search for something until you have five or less results.
> Switch results to table format if there are five items or less

- assets/items.js
- components/LatLngSelector.vue
- components/global/PrecipitationFrequency.vue
- package-lock.json
- package.json
- plugins/plotly.client.ts
- stores/data.ts
This PR does a few things:
- Adds Plotly as a Nuxt plugin
- Adds a new `data` store that is meant to be a one-stop shop for Data API interactions
- Adds a new "Precipitation frequency" ARDAC item that uses the existing `LatLngSelector` component to generate Plotly charts based on lat/lon inputs
To test, do an `npm install`, then load the full view for the "Precipitation frequency" item and interact with the lat/lon input to generate charts. The `LatLngSelector` component already checks for malformed and out-of-BBOX lat/lons, but it's also now rigged up to react to nodata responses/values received from the Data API, such as precipitation frequency requests that are over the ocean (e.g., 63, -167).
> Add example Plotly chart that reacts to lat/lon input

- pages/tag/[tag].vue
- scripts/csv2json.cjs
- types/custom.d.ts
- types/tags.d.ts
This PR basically does the same thing for item tags that we did for slugs. It defines a new `Tag` type with a list of possible values generated using `csv2json.cjs` (with the necessary modifications).
I've also confirmed that, with this change, VS Code now autocompletes tags when editing `items.ts` and underlines invalid tags.
To test, make sure the app runs like before. Then try adding an invalid tag to an item in `items.ts` and make sure the TypeScript police catch you. 🚨
> Implement Tag type with possible values

- components/global/LandfastSeaIce.vue
Closes #53.
This PR is just a simple word replacement (March → June) so that the Landfast Sea Ice Extent intro text matches the available map layers. To test, view the Landfast Sea Ice Extent ARDAC item here: http://localhost:3000/item/landfast-sea-ice
> Fix month in Landfast Sea Ice Extent intro text

- assets/items.ts
- components/FrontPage/Main.vue
- components/FrontPage/Section/Climate.vue
- components/IndicatorsCmip6Chart.vue
- components/IndicatorsCmip6ChartControls.vue
- components/global/IndicatorDwCmip6.vue
- components/global/IndicatorFtcCmip6.vue
- components/global/IndicatorRx1day.vue
- components/global/IndicatorRx1dayCmip6.vue
- components/global/IndicatorSuCmip6.vue
- stores/chart.ts
- stores/data.ts
- types/custom.d.ts
- types/slugs.d.ts
This PR consists of the maps + charts of the following CMIP6 variables available through our development API:
- Freeze/Thaw Cycle
- Summer Days
- Deep Winter Days
- Maximum 1-day Precipitation
To test, run a local instance of the Data API from the `cmip6_indicators` branch, pointing at Zeus:
```
cd data-api
git checkout cmip6_indicators
git pull --ff-only
export FLASK_APP=application.py
export API_RAS_BASE_URL=https://zeus.snap.uaf.edu/rasdaman/
pipenv run flask run
```
Then run this branch of the ARDAC Explorer against the local API, and against Zeus for its Rasdaman server:
```
cd ardac-explorer
git checkout implement_cmip6_items
export SNAP_API_URL=http://localhost:5000
export RASDAMAN_URL=https://zeus.snap.uaf.edu/rasdaman/ows
npm run dev
```
Then view the available CMIP6 items here: …
> Implement map + chart for the 4 currently available CMIP6 indicator ARDAC items

- app.vue
- pages/index.vue
Closes #51.
This PR adds S3 permalink support in a way that is similar to how our other webapps (Northern Climate Reports, Arctic-EDS) do it, but adapted to work with Nuxt 3.
While permalinks do already work when running the app locally, the issue with S3 is that since the webapp is served as a static website, all traffic needs to land on `index.html` to access the app before being routed to a specific path within the app. To do this, we use S3 settings to route all 404s to `index.html` and then reroute them back to the requested webapp path.
I initially implemented this rerouting trick in `pages/index.vue`, but when doing so, it failed to recognize when I requested a non-existing file path and silently routed to the front page of the app. To fix this, I had to create an `app.vue` and put …
> Redirect S3 hashbang path redirects to their corresponding Nuxt paths

- components/DegreeDaysChart.vue
This PR updates the shared `DegreeDaysChart.vue` component with the latest changes to the API output, including the new `modeled_baseline` key instead of `historical`.
> Update degree days chart code with updated API output

- components/global/DdBelow0.vue
- components/global/DdBelow65.vue
- components/global/FreezingIndex.vue
- components/global/ThawingIndex.vue
Closes #86.
This PR simply replaces all "ERA-Interim" references in the intro/explanatory text of degree days items with "Daymet".
To test, make sure there are no references to "ERA-Interim" on the following items:
http://localhost:3000/item/dd-below-65
http://localhost:3000/item/dd-below-0
http://localhost:3000/item/thawing-index
http://localhost:3000/item/freezing-index
> Replace "ERA-Interim" text references in degree days items with "Daymet"

- components/global/SeaIceConcentration.vue
Closes #76.
This PR simply replaces the "1980-2000" year range in the intro text of the Sea Ice Concentration item with "1850-2000" to accurately reflect the displayed map layers.
To test, look at the Sea Ice Concentration here and verify the above:
http://localhost:3000/item/sea-ice-concentration
> Fix year range in intro text of Sea Ice Concentration item

- components/global/IndicatorFtcCmip6.vue
- components/global/IndicatorRx1dayCmip6.vue
- stores/map.ts
- types/custom.d.ts
Closes #63.
This PR adds the Natural Earth coastline layer to problematic maps (CMIP6 Freeze/Thaw Cycle and CMIP6 Maximum 1-day Precipitation) on top of the data layers. It's the same coastline layer we are already using in Northern Climate Reports that is hosted from GeoServer. This adds more context to otherwise-unintelligible CMIP6 indicator maps (see screenshot in #63).
To test & see the benefits of this change, view these CMIP6 indicator maps:
http://localhost:3000/item/indicator-ftc-cmip6
http://localhost:3000/item/indicator-rx1day-cmip6
Also verify that the coastline layer does not show up on the maps for other ARDAC items. This PR originally added the coastline to all maps in ARDAC Explorer, but I decided against this because it made the data layer harder to see on some maps, …
> Add Natural Earth coastline layer to problematic maps

- components/Gimme.vue
- components/LoadIndicator.vue
Closes #48.
This PR adds a progress bar below the place selector for all applicable ARDAC items (all ARDAC items that fetch data from the API for a chart or table).
To test, select a location to generate a chart for several different ARDAC items. Observe that:
- The progress bar is only visible while the app is actively trying to fetch data from the API.
- The progress bar disappears as soon as the chart or table loads.
- If there's an error (like an invalid location), the progress bar disappears as soon as the error is detected.
> Add a progress bar when chart/table data is loading

- components/IndicatorsCmip6ChartControls.vue
Closes #93.
Not all scenarios (SSPs) are available for every model from our CMIP6 Indicators Data API endpoint. Invalid model + SSP combinations are set to `null` in the API output. This PR prevents users from accidentally selecting an invalid model + SSP combination from the CMIP6 Indicator chart dropdown menus by graying out SSPs that are unavailable for the selected model.
If a user first selects an SSP, then selects a model that does not support that SSP, I've added some code to revert back to the default SSP (SSP5-8.5) since this scenario is present for all models.
I've also updated the available model choices to reflect our current API output since these seem to have changed somewhere along the way.
To test, enter a location to load a chart for any of the CMIP6 Indicators ARDAC …
> Disable invalid model/scenario combos and update CMIP6 model options

- components/HydrologyChartControls.vue
- components/global/HydrologyIswe.vue
Closes #68.
This PR mostly just changes the default month for all hydrology charts from June to March. Without this change, snow water equivalent charts were almost always all-zero on initial load.
To see the change, load the app and go to this URL:
http://localhost:3000/item/hydrology-iswe
Enter Fairbanks into the place selector and notice that the snow water equivalent chart loads with a bunch of non-zero values, whereas if you select the month of June the chart is all-zero.
You'll also notice that the ice water equivalent chart is all-zero for Fairbanks regardless of what month you choose. This is because ice water equivalent is zero for Fairbanks (and most locations) for all months. This agrees with the ice water equivalent maps on the same page. Incidentally, I've also fixed the …
> Change default month for hydrology charts from June to March, and fix ice water equivalent map legend

- components/BetaNotice.vue
- layouts/default.vue
- layouts/home.vue
- stores/store.ts
Closes #49.
This PR adds a beta notification banner near the top of the webapp, across all pages. The banner can be closed and this setting persists in the Pinia store until the app is reloaded.
I experimented with the placement of this banner and ultimately it seems to fit best (aesthetically and thematically) right below the "edition" component.
To test, load the app and:
- Visit a few different pages to confirm that the beta banner shows up everywhere
- Close the banner
- Confirm that the banner no longer appears on any page until you reload the app
> Add beta notification banner

- components/DegreeDaysChart.vue
- components/IndicatorsCmip6Chart.vue
- components/PermafrostChart.vue
- components/global/WetDaysPerYear.vue
- utils/math.js
Closes #65.
This PR addresses overaggressive rounding in charts where we calculate the decadal mean from yearly values client-side. Look at the hovertext in the screenshot below to see what I mean:
Since the mean is rounded to a whole number, `0`, it ends up being larger than the max number. And because of this, the plot marker is placed above/outside of the error bars.
To solve this, I've created a new utility function, `precisionMean`, that calculates the difference between the min/max values and rounds the mean to 1 decimal of precision if the difference is less than 10. If the difference is greater than (or equal to) 10, it continues to round to a whole number.
Here's a screenshot of the same chart using the new `precisionMean` function:
To test, run the webapp against Zeus:
``` …
```
> Choose chart mean rounding precision based on value range

- components/PermafrostChartControls.vue
- components/global/PrecipitationFrequency.vue
Closes #95.
This PR fixes a couple bugs:
- Hides the chart input (scenario dropdown) for all permafrost items when data is either still loading or not available
- Hides the download links for the Precipitation Frequency item when data is either still loading or not available
The easiest way to test this is to set your `SNAP_API_URL` environment variable to something bogus to simulate a data fetch error. For example:
```
export SNAP_API_URL=http://pizza.pizza:5000
```
Then, run the app and enter a location into the place selector for each of the following ARDAC items:
http://localhost:3000/item/permafrost-magt
http://localhost:3000/item/permafrost-base-top
http://localhost:3000/item/permafrost-talik
http://localhost:3000/item/precipitation-frequency
In each case, the data fetch will fail, …
> Hide chart inputs and download links when there is no data

- nuxt.config.ts
Closes #55.
This PR adds Umami analytics to the webapp.
To test:
- Boot up your local umami Vagrant VM with `vagrant up`. If you no longer have this handy, follow the setup instructions described here https://github.com/ua-snap/nccwsc-projects/pull/154.
- Visit your local Umami's dashboard at http://localhost:9999/
- Authenticate through local Umami's web interface if necessary, using the Umami web interface credentials in Bitwarden
- Go to the "Settings" page and create a new website for "ARDAC Explorer" using its real domain (doesn't really matter)
- Modify the webapp code in the `add_umami` branch
- Change the Umami `src` to `http://localhost:9999/script.js`
- Replace the Umami website ID with the one that was generated when you created the "ARDAC Explorer" website
- Comment out the …
> Add Umami analytics

- assets/items.ts
- components/Cmip6MonthlyChart.vue
- components/Cmip6MonthlyChartControls.vue
- components/Map.vue
- components/global/EvaporationCmip6.vue
- components/global/OceanographyCmip6.vue
- components/global/PrecipitationCmip6.vue
- components/global/SeaLevelPressureCmip6.vue
- components/global/SolarRadiationCloudCoverCmip6.vue
- components/global/TemperatureCmip6.vue
- components/global/WindCmip6.vue
- stores/data.ts
- types/custom.d.ts
- types/slugs.d.ts
Closes #145.
Xref: https://github.com/ua-snap/data-api/pull/472
This PR implements six new "data x-ray" items based on the new CMIP6 monthly coverage on Apollo.
To test, run the data-api off the `cmip6_monthly` branch, pointed at Apollo:
```
cd data-api
git checkout cmip6_monthly
export FLASK_APP=application.py
export API_RAS_BASE_URL=https://apollo.snap.uaf.edu/rasdaman/
pipenv run flask run
```
Then run ARDAC Explorer, pointed at your local API and Apollo:
```
cd ardac-explorer
git checkout cmip6_monthly
export SNAP_API_URL=http://localhost:5000
export RASDAMAN_URL=https://apollo.snap.uaf.edu/rasdaman/ows
npm run dev
```
Then, test drive the maps & charts on the following items:
http://localhost:3000/item/temperature-cmip6
http://localhost:3000/item/wind-cmip6 …
> Add six new CMIP6 data x-ray items

- components/global/SolarRadiationCloudCoverCmip6.vue
Closes #149.
This PR simply adds the missing Cloud Area Fraction (Cloud Cover) map layer for the year 2000 to the following item:
http://localhost:3000/item/solar-radiation-cloud-cover-cmip6
To test, run the app and verify that the "August 2000, HadGEM3-GC31-MM" layer works as expected.
> Add Cloud Area Fraction layer for the year 2000

- components/global/IndicatorRx1dayCmip6.vue
This PR simply updates the y-axis unit label in the CMIP6 "Maximum 1-day Precipitation" charts from `m` to `㎜`. This is necessary because the new `cmip6_indicators_new` coverage has precipitation values that have already been converted millimeters, whereas the old `cmip6_indicators` coverage used meters.
> Fix units in CMIP6 rx1day chart from m to mm

- components/global/StoryArcticClimateDataNode.vue
This PR updates the CMIP6 Summer Days map on the Arctic Climate Data Node data story to:
- Reflect the different model axis mapping from the new `cmip6_indicators` coverage. `GFDL-ESM4` is now at position 3, not 4, so the page is currently not correct.
- Updates the CMIP6 Summer Days map on the page to use the model `TaiESM1` (at model axis position 11), same as the CMIP6 indicator x-ray items, since this model produces more interesting maps and more interesting changes between eras.
To test, run the app and look at the CMIP6 Summer Days map layers & surrounding text on this page:
http://localhost:3000/item/story-arctic-climate-data-node
> Update CMIP6 Summer Days map on Arctic Climate Data Node story

- components/global/StoryArcticClimateDataNode.vue
Closes #142 
Testing:
- Go to ACDN story
- Under the "What does ACDN offer researchers?" section, scroll down to where the text reads, "see available data."  Click.
- It goes to the interactive table of models/scenarios/variables, and has a new wee blurb which links to the CMIP6 topic page
> Adjust link in story, add link to CMIP6 topic page

- components/HydrologyChart.vue
- components/HydrologyChartControls.vue
- components/IndicatorsCmip6Chart.vue
- components/IndicatorsCmip6ChartControls.vue
- components/PermafrostChart.vue
- components/PermafrostChartControls.vue
Closes #118 
Testing:
- Point app at dev API endpoint: `export SNAP_API_URL=https://development.earthmaps.io`
- For each of these, keep the dev console open and verify that
1. the data fetch works / charts populate and
2. only one HTTP request is fired.  Test all these:
http://localhost:3000/item/permafrost-base-top
http://localhost:3000/item/permafrost-magt
http://localhost:3000/item/indicator-su-cmip6
(Hydrology needs to be tested later, see #162)
> Reduce duplicate API requests triggered when charts are drawn

- components/Cmip6MonthlyChart.vue
- components/IndicatorsCmip6Chart.vue
- utils/math.js
Refs #154 
This PR clamps the y-axis when switching between scenario/model combinations, so that it's easier to visually compare how different models look for the same variable/indicator.  This currently applies only to the CMIP6 variables and CMIP6 indicators.
Testing:
- `export SNAP_API_URL=https://development.earthmaps.io/`
- For every CMIP6 variable, try switching between models/scenarios: the y-axis should be fixed.  Changing month will recalibrate the y-axis.  (y-range is computed on a per-chart basis, so for Temp, the mean/max/min will all have different y-ranges.
- For every CMIP6 indicator, switch model/scenarios.  Y axis will stay clamped.
> Clamp yaxis for (some) xray items

- components/global/HydrologyIswe.vue
Closes #176.
This PR updates the map legends for the IWE and SWE maps to reflect the new WCPS queries. Previously, the WCPS queries were adding IWE and SWE values across all months for three decades, and dividing by 3, to show an annual cumulative value. This was based on my misunderstanding that it was appropriate to sum these values.
Since IWE and SWE reflect snapshots in time, it doesn't make sense to add them together, so I've updated the WCPS queries to divide by 36 (3 decades * 12 months), and changed the colormap thresholds accordingly. This PR simply updates the color map thresholds and tweaks the text a little but to emphasize that these are monthly mean values.
To test, run ARDAC Explorer against the development API:
```
export SNAP_API_URL=https://development.earthmaps.io
npm …
```
> Update IWE/SWE map legends to reflect fixed WCPS queries

- components/Cmip6MonthlyChart.vue
Closes #170.
This PR fixes console errors that occur when Plotly attempts to purge a chart that had not previously loaded. This fix applies to only the CMIP6 monthly charts, which are also the only charts that exhibit this problem due to the conditional chart loading we have in place since some CMIP6 models don't provide every variable (e.g., `tasmin` and `tasmax`).
To test, run ARDAC Explorer against the development API:
```
export SNAP_API_URL=https://development.earthmaps.io
npm run dev
```
Then make sure your browser's console is open, then visit:
http://localhost:3000/item/temperature-cmip6
Enter a location (e.g., "Fairbanks") to load the charts for the default TaiESM1 model, then select the model above it (NorESM2-MM), then select the model above that (MRI-ESM2-0). If you see no …
> Purge CMIP6 Plotly charts only if they successfully loaded previously

- components/HydrologyChart.vue
- components/HydrologyChartControls.vue
- components/global/HydrologyEvap.vue
- components/global/HydrologyGlacierMelt.vue
- components/global/HydrologyIswe.vue
- components/global/HydrologyRunoff.vue
- components/global/HydrologySm.vue
- components/global/HydrologySnowMelt.vue
- types/custom.d.ts
Closes #146.
This PR adds the same model selection feature we have for other ARDAC's items to all hydrology charts.
To test, first uncomment the hydrology slugs in `slugs.d.ts` so the corresponding items are accessible:
```
| 'hydrology-evap'
| 'hydrology-glacier-melt'
| 'hydrology-iswe'
| 'hydrology-runoff'
| 'hydrology-sm'
| 'hydrology-snow-melt'
```
Then run ARDAC Explorer against the development API:
```
export SNAP_API_URL=https://development.earthmaps.io
npm run dev
```
Then enter a location (e.g, "Fairbanks") into any of these hydrology data x-ray items to load the charts, then experiment with selecting different models to verify that the charts react accordingly:
http://localhost:3000/item/hydrology-evap
http://localhost:3000/item/hydrology-glacier-melt …
> Add model selection feature to all hydrology charts

- components/global/EvaporationCmip6.vue
I noticed while reviewing PR #195 that I had made a mistake months ago in the intro text for some CMIP6 items, claiming that map layers were shown for "25-year intervals from 1950–2000", when it should say "25-year intervals from 1950–2100". All affected CMIP6 data x-ray items will be fixed in #195, except for Evaporation, which is unrelated to PR #195, but fixed here. Self-merging because this is a trivial change.
> Fix year range in intro text for CMIP6 Evaporation item

- components/Cmip6MonthlyChart.vue
- components/Cmip6MonthlyChartControls.vue
- components/Gimme.vue
- components/global/PrecipitationCmip6.vue
- components/global/SeaIceCmip6.vue
- components/global/SnowCmip6.vue
- nuxt.config.ts
- types/custom.d.ts
This PR adds the Sea Ice and Snow items to ARDAC at:
http://localhost:3000/item/sea-ice-cmip6
http://localhost:3000/item/snow-cmip6
This includes the pan-arctic maps, Xray blurb, charts, and the ability to get both CSVs and JSONs for each of the datasets. 
Try experimenting with a few different places to get different charts and make sure that all of the maps are working as expected.
> Adds the CMIP6 Sea Ice and Snow items

- components/global/SummaryLandfastSeaIce.vue
This PR simply updates the coverage name used in the map for the Landfast Sea Ice Extent data story. On Apollo, this coverage was named `ardac_landfast_sea_ice_mmm`, but it is named `ardac_beaufort_landfast_sea_ice_mmm` on Zeus. The text below the map specifically mentions that the map shows "seaward landfast ice edge (SLIE) for the Beaufort Sea region", so this is the correct coverage (as opposed to `ardac_chukchi_landfast_sea_ice_mmm`). Self-merging because this is a very trivial update.
The rest of the diff is simply due to enforcement of Prettier formatting.
> Update Landfast Sea Ice Extent data story coverage name

- components/global/ClimateBeetleProtection.vue
This PR simply replaces the word "risk" with "climate protection" in the chart intro text for the beetle data x-ray item. All other diff changes are due to word-rewrapping.
> Fix beetle text from "risk" to "climate protection" in chart intro

- components/Cmip6MonthlyChart.vue
- components/global/EvaporationCmip6.vue
This PR modifies the following parts of the CMIP6 Evaporation data x-ray item to deal with tiny values better, removing the need to use the `µ` (one millionth) character:
- The map legend
- Chart y-axis label, y-axis tick marks, and hover text
For the map legend, it's sufficient to simply remove the `µ` character and change the units to "1 × 10⁻⁶ kg m⁻² s⁻¹", since `10⁻⁶` communicates that values are of the "one millionth" scale. No changes were needed to the WMS color maps or anything.
For the chart, the y-axis label was updated to use "1 × 10⁻⁶ kg m⁻² s⁻¹" for the units, but I also needed to multiply the values by 1,000,000 to remove the `µ` y-axis tick labels and hovertext values. This was implemented as an optional `multiplier` prop that can be passed into `Cmip6MonthlyChart.vue`, so …
> Update Evaporation unit scale to remove µ

- components/global/SnowCmip6.vue
This PR simply removes the duplicated units shown in the CMIP6 snow graphs.
Closes #210
> Removes the duplicated units shown in the title and Y-axis of the CMIP6 snow graphs.

- components/Gimme.vue
- components/global/SeaIceCmip6.vue
Closes #211.
This PR disables community queries on the CMIP6 Sea Ice item by adding a new `communitiesEnabled` prop to the `Gimme` component that, when set to `false`, disables communities entirely and adjusts user prompts and placeholder text accordingly.
Specific information about why communities are disabled for the CMIP6 Sea Ice item has been added to the `SeaIceCmip6.vue` directly. Just a short blurb that says:
> Coastal community queries are not supported due to the coarse resolution of this dataset.
To test, compare the production vs. local versions of this ARDAC item to see the differences:
http://localhost:3000/item/sea-ice-cmip6
https://arcticdatascience.org/item/sea-ice-cmip6
> Disable community queries for CMIP6 Sea Ice item and explain why to users

- components/global/SummaryLandfastSeaIce.vue
Closes #208.
This PR simply updates the URL of the "Mahoney et al. 2005" paper link on the Landfast Sea Ice Extent data story to be the same as the URL we're using on the Landfast Sea Ice Extent data x-ray item.
> Fix broken link to paper on Landfast Sea Ice data story

- components/Gimme.vue
I realized while poking around ARDAC Explorer locally that I neglected to make `communitiesEnabled` an optional prop in PR #214. Everything works as intended regardless because `communitiesEnabled` is immediately set to a default value if not set, but this fixes a JavaScript warning in the console. This is a very trivial change, so I am going to self-merge this.
> Make communitiesEnabled an optional component prop

- components/global/StoryArcticClimateDataNode.vue
Closes #223.
This PR updates the intro text and CMIP6 model & scenario tables on the ACDN data story page here:
http://localhost:3000/item/story-arctic-climate-data-node
In production, the intro text says:
> A curated suite of CMIP6 models and scenarios that perform best in Alaska and the pan–Arctic: These include 13 global climate models, 4 emissions scenarios, and 15 variables.
But we actually have 12 models and 18 variables available through ARDAC Explorer currently, so this PR updates that intro text.
The "Overview of CMIP6 data in the ACDN" table further down the page was also due for an update. I've updated the table like so:
- Removed the unavailable E3SM-Project E3SM-2-0, ACCESS-CM2, and CESM2-WACCM models
- Changed MPI-ESM1-2-LR to MPI-ESM1-2-HR to match the Data API output and …
> Update ACDN data story with current batch of CMIP6 models/variables/frequency

- components/Cmip6MonthlyChart.vue
Closes #253.
This PR fixes a problem that appears on the CMIP6 Temperature charts where, if `tasmin` and `tasmax` data are not available for the selected model, it displays empty min/max temperature charts instead of hiding these charts completely.
I remembered having solved this problem once before, but it turns out this line of code that was added later had introduced the bug:
https://github.com/ua-snap/ardac-explorer/blob/ef4c729b8f8b12c553d1162727f20d114903fa39/components/Cmip6MonthlyChart.vue#L116
This line of code was multiplying `value` by `multiplier` without first checking to see if the value was `undefined`. There is already some code in place to determine if all chart values are `undefined`, and to hide the chart if so. But attempting to multiply `undefined` by a number …
> Fix CMIP6 empty chart bug

- components/Cmip6MonthlyChartControls.vue
Closes #252.
This PR simply adds a little more logic to make sure the "Scenario" dropdown changes to a scenario that is actually available for the selected model. Previously, we solved this by switching back to the `defaultScenario` if necessary, but with the introduction of the E3SM* models, there is no longer a particular scenario that works across all models, so this solution is a bit more dynamic to make the user interface work seamlessly.
It's hard to test this without bringing the E3SM* models in, but that has been implemented in a separate branch/PR. So, there are some extra testing steps here.
To test, run the Data API from the `add_e3sm` branch while pointed at Apollo:
```
cd data-api
git checkout add_e3sm
export FLASK_APP=application.py
export …
```
> Switch to an available scenario if selected (or default) scenario does not exist

- components/global/SnowCmip6.vue
- components/global/StoryArcticClimateDataNode.vue
Closes #251.
Xref: https://github.com/ua-snap/data-api/pull/571
Xref: https://github.com/ua-snap/data-api/pull/567
This PR simply renames the `swe` CMIP6 key to `snw` throughout the code. This key was changed in the latest iteration of the `cmip6_monthly` coverage. See https://github.com/ua-snap/data-api/pull/567 (near the end of the PR description) for details.
I've also copied the`cmip6_monthly` coverage's `ardac_swe` WMS style to a new `ardac_snw` style on Apollo with the same WCPS query + color map. I'll create a PR for this in the rasdaman-ingest repo soon.
To test, run both the Data API and ARDAC Explorer from their respective `cmip6_snw_key` branches:
```
cd data-api
export FLASK_APP=application.py
export API_RAS_BASE_URL=https://apollo.snap.uaf.edu/rasdaman/
pipenv run flask run …
```
> Update cmip6_monthly "swe" key to "snw" throughout code

- app.vue
This is a simple PR that fixes the router issues we were seeing when the site was on an S3 bucket website. The issue was that when we used the S3 redirection rules to add a hashbang to fool S3 into allowing an SPA, we were attempting to remove the hashbang before the vue-router was fully initialized on page load. This was resulting in NuxtLinks being broken all over the site.
This simple fix waits until everything is loaded before redirecting to the correct URL. For testing, try reloading in your browser from any tag or item, and verify that the correct redirection happens along with the ability to choose any of the tags or other NuxtLinks. 
For example, start here: http://climate.arcticdatascience.org/tag/Precipitation
> Fixes router failure when in static mode in S3 bucket.

- components/Gimme.vue
Gives a message below the Gimme box if no communities were found containing the given substring. 
To test, start your local API on the main branch and point this branch at it:
`export SNAP_API_URL=http://localhost:5000`
Go to any X-ray item and type in a bad substring and note that the Gimme box returns a message below it that states that "No communities found with that substring."
Closes #283
> Provide message to user if no communities are found with given substring

- components/Item/Brief.vue
- components/Item/Text.vue
- components/Item/TextPicture.vue
- components/Tagbar.vue
This PR removes the Umami analytics special parameters from all `NuxtLink` components to allow for the website when accessed from its main site to act as a single page application. Without this change, we were seeing the `NuxtLink` client-side routing being intercepted by Umami and sent as a plain anchor link route, reloading the page on each click. This change will only impact the site at https://arcticdatascience.org as we explicitly tell Umami to only track from that URL.
While this change does mean that we don't have explicit events shown in Umami, we still get the page views which shows the same information.
> Removes Umami events from NuxtLinks to allow for client-side routing.

- components/NotebookTemplate.vue
- components/global/NotebookPrecipPoly.vue
Test: pick "see more" from the menu-tag-bar, pick Programming, go to any (implemented) programming item.  Observe that with this PR, there's no "run this notebook online" link at the upper right of the item or at the bottom of any of them.
When this ticket is reviewed for release notes, include the task of turning off the notebook server and surplussing it as well.
> Removes link to "run this notebook online"
